version: '3'
services:
  web:
    image: gitea/gitea:1.12.4
    volumes:
      - ./data:/data
    environment:
      - USER_UID=1000
      - USER_GID=1000
       - DB_TYPE=mysql
       - DB_HOST=db:3306
       - DB_NAME=gitea
       - DB_USER=gitea
       - DB_PASSWD=NotSoSecretUserPassword
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db
    restart: always
  db:
    image: mariadb:10
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=SuperSecretAdminPassword
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=NotSoSecretUserPassword
    volumes:
      - ./db/:/var/lib/mysql
